apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mydockerhub/backend:latest
        env:
          - name: DB_HOST
            value: "db-service"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "rootpassword"
          - name: DB_NAME
            value: "angular"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
